name: Run tests

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**/*.md'

jobs:
  run_tests:
    runs-on: ubuntu-latest

    env:
      SOME_VAR: "SOME_VALUE"

    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
        with: 
          submodules: recursive
      -
        name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      -
        name: Test cd
        run: |
          cd somefolder
          python3 module.py
      - 
        name: Test after cd
        run: |
          python3 main.py
      - 
        name: Install opensfm
        run: |
          sudo apt install libeigen3-dev \
              libopencv-dev \
              libceres-dev \
              python3-dev \
              python3-numpy \
              python3-opencv \
              python3-pip \
              python3-pyproj \
              python3-scipy \
              python3-yaml \
              curl
          cd libs/opensfm
          git checkout 7d1878460116fd5b8c5083f676b02524470af282
          pip3 install -r requirements.txt
          python3 setup.py build
          python3 setup.py install
      -
        name: Test opensfm
        run: |
          python3 -c "import opensfm; print(opensfm)"
