name: Run tests

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**/*.md'

jobs:
  run_tests:
    runs-on: ubuntu-latest

    env:
      SOME_VAR: "SOME_VALUE"

    container:
      image: vsvasya/baseimage-cpu
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
        with: 
          submodules: recursive
      -
        name: Install our dependencies
        run: |
          pip3 install poetry wheel
          poetry install
      - 
        name: dummy test
        run: |
          python3 -c "import opensfm"
      - name: currentdir
        run: |
          echo $(pwd)
      - name: opensfm sample test
        run: |
          cd /build/OpenSfM
          bin/opensfm_run_all data/berlin
