name: Run tests

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**/*.md'

jobs:
  run_tests:
    runs-on: ubuntu-latest

    env:
      SOME_VAR: "SOME_VALUE"

    container:
      image: vsvasya/opensfm
    steps:
      - 
        name: dummy test
        run: |
          python3 -c "import opensfm"
      - name: opensfm sample test
        run: |
          cd /build/OpenSfM
          bin/opensfm_run_all data/berlin
